# Generated by Django 6.0.2 on 2026-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate relative to base currency (USD)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='$', max_length=10),
        ),
    ]
