# Generated by Django 6.0.2 on 2026-02-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Nairobi CBD, Nairobi Suburbs, Rest of Kenya', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_free_delivery', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount for free delivery', max_digits=10, null=True)),
                ('estimated_days_min', models.PositiveIntegerField(default=1)),
                ('estimated_days_max', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomizableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_cover_text', models.BooleanField(default=True)),
                ('allow_cover_material', models.BooleanField(default=True)),
                ('allow_cover_color', models.BooleanField(default=True)),
                ('allow_page_type', models.BooleanField(default=True)),
                ('allow_page_count', models.BooleanField(default=False)),
                ('available_materials', models.CharField(default='standard,leather,vegan_leather', max_length=200)),
                ('available_colors', models.CharField(default='Black,Brown,Navy,Burgundy,Forest Green', max_length=500)),
                ('available_page_types', models.CharField(default='blank,lined,dotted,grid', max_length=200)),
                ('text_emboss_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('leather_price', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('vegan_leather_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('extra_pages_price', models.DecimalField(decimal_places=2, default=0.05, help_text='Per additional page', max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customizable_options', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Customizable Product',
                'verbose_name_plural': 'Customizable Products',
            },
        ),
        migrations.CreateModel(
            name='JournalCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this customization option', max_length=100)),
                ('cover_text', models.CharField(blank=True, help_text='Text to emboss on cover', max_length=100)),
                ('cover_material', models.CharField(choices=[('standard', 'Standard'), ('leather', 'Genuine Leather'), ('vegan_leather', 'Vegan Leather'), ('fabric', 'Fabric'), ('canvas', 'Canvas')], default='standard', max_length=20)),
                ('cover_color', models.CharField(blank=True, max_length=50)),
                ('page_type', models.CharField(choices=[('blank', 'Blank'), ('lined', 'Lined'), ('dotted', 'Dotted'), ('grid', 'Grid'), ('mixed', 'Mixed (Lined + Blank)')], default='lined', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('session_key', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.deliveryzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customization', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='wishlisted_by', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customization', models.JSONField(blank=True, help_text='Custom options for journals', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'unique_together': {('cart', 'product', 'customization')},
            },
        ),
    ]
